const actionTypes = {
  ADD_BOOK: "ADD_BOOK",
  STORE_BOOK_ISBN: "STORE_BOOK_ISBN",
  DELETE_BOOK: "DELETE_BOOK",
  INCREASE_BOOK_COUNT: "INCREASE_BOOK_COUNT",
  DECREASE_BOOK_COUNT: "DECREASE_BOOK_COUNT",
  SET_SCANNED: "SET_SCANNED",
  RESET_SCANNED: "RESET_SCANNED",
  SET_HAS_PERMISSION: "SET_HAS_PERMISSION",
  INCREMENT_CAMERA_KEY: "INCREMENT_CAMERA_KEY",
};

export default actionTypes;
