const actionTypes = {
  ADD_BOOK: "ADD_BOOK",
  DELETE_BOOK: "DELETE_BOOK",
  INCREASE_BOOK_COUNT: "INCREASE_BOOK_COUNT",
  DECREASE_BOOK_COUNT: "DECREASE_BOOK_COUNT",
};

export default actionTypes;
