const actionTypes = {
  ADD_BOOK: "ADD_BOOK",
  UPDATE_BOOK: "UPDATE_BOOK",
  DELETE_BOOK: "DELETE_BOOK",
  GET_ALL_BOOKS: "GET_ALL_BOOKS",
  GET_ALL_BORROWINGS: "GET_ALL_BORROWINGS",
  SET_TITLE: "SET_TITLE",
  SET_AUTHOR: "SET_AUTHOR",
  SET_GENRE: "SET_GENRE",
};

module.exports = actionTypes;
